// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: compute_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文本提取
type ExtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_compute_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ExtractRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

type ExtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextContent   string                 `protobuf:"bytes,1,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_compute_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractResponse) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

// 抄袭检测
type PlagiarismRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// map<学生ID, 合并后的纯文本>
	StudentTexts  map[string]string `protobuf:"bytes,1,rep,name=student_texts,json=studentTexts,proto3" json:"student_texts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlagiarismRequest) Reset() {
	*x = PlagiarismRequest{}
	mi := &file_compute_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlagiarismRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlagiarismRequest) ProtoMessage() {}

func (x *PlagiarismRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlagiarismRequest.ProtoReflect.Descriptor instead.
func (*PlagiarismRequest) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{2}
}

func (x *PlagiarismRequest) GetStudentTexts() map[string]string {
	if x != nil {
		return x.StudentTexts
	}
	return nil
}

type PlagiarismResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 返回查重报告的 JSON 字符串表示: {"student_1": [report1...], "student_2": [...]}
	PlagiarismResultsJson string `protobuf:"bytes,1,opt,name=plagiarism_results_json,json=plagiarismResultsJson,proto3" json:"plagiarism_results_json,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlagiarismResponse) Reset() {
	*x = PlagiarismResponse{}
	mi := &file_compute_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlagiarismResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlagiarismResponse) ProtoMessage() {}

func (x *PlagiarismResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlagiarismResponse.ProtoReflect.Descriptor instead.
func (*PlagiarismResponse) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{3}
}

func (x *PlagiarismResponse) GetPlagiarismResultsJson() string {
	if x != nil {
		return x.PlagiarismResultsJson
	}
	return ""
}

// AIGC
type AIGCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextContent   string                 `protobuf:"bytes,1,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIGCRequest) Reset() {
	*x = AIGCRequest{}
	mi := &file_compute_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIGCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIGCRequest) ProtoMessage() {}

func (x *AIGCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIGCRequest.ProtoReflect.Descriptor instead.
func (*AIGCRequest) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{4}
}

func (x *AIGCRequest) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

type AIGCResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AigcReportJson string                 `protobuf:"bytes,1,opt,name=aigc_report_json,json=aigcReportJson,proto3" json:"aigc_report_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AIGCResponse) Reset() {
	*x = AIGCResponse{}
	mi := &file_compute_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIGCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIGCResponse) ProtoMessage() {}

func (x *AIGCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIGCResponse.ProtoReflect.Descriptor instead.
func (*AIGCResponse) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{5}
}

func (x *AIGCResponse) GetAigcReportJson() string {
	if x != nil {
		return x.AigcReportJson
	}
	return ""
}

// 作业评分
type GradeRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	StudentId             string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Question              string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	RubricJson            string                 `protobuf:"bytes,3,opt,name=rubric_json,json=rubricJson,proto3" json:"rubric_json,omitempty"`
	StudentText           string                 `protobuf:"bytes,4,opt,name=student_text,json=studentText,proto3" json:"student_text,omitempty"`
	PlagiarismReportsJson string                 `protobuf:"bytes,5,opt,name=plagiarism_reports_json,json=plagiarismReportsJson,proto3" json:"plagiarism_reports_json,omitempty"`
	AigcReportJson        string                 `protobuf:"bytes,6,opt,name=aigc_report_json,json=aigcReportJson,proto3" json:"aigc_report_json,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GradeRequest) Reset() {
	*x = GradeRequest{}
	mi := &file_compute_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeRequest) ProtoMessage() {}

func (x *GradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeRequest.ProtoReflect.Descriptor instead.
func (*GradeRequest) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{6}
}

func (x *GradeRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GradeRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *GradeRequest) GetRubricJson() string {
	if x != nil {
		return x.RubricJson
	}
	return ""
}

func (x *GradeRequest) GetStudentText() string {
	if x != nil {
		return x.StudentText
	}
	return ""
}

func (x *GradeRequest) GetPlagiarismReportsJson() string {
	if x != nil {
		return x.PlagiarismReportsJson
	}
	return ""
}

func (x *GradeRequest) GetAigcReportJson() string {
	if x != nil {
		return x.AigcReportJson
	}
	return ""
}

type GradeResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotalScore             float32                `protobuf:"fixed32,1,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	Feedback               string                 `protobuf:"bytes,2,opt,name=feedback,proto3" json:"feedback,omitempty"`
	MergedContent          string                 `protobuf:"bytes,3,opt,name=merged_content,json=mergedContent,proto3" json:"merged_content,omitempty"`
	CodeDocMatchReportJson string                 `protobuf:"bytes,4,opt,name=code_doc_match_report_json,json=codeDocMatchReportJson,proto3" json:"code_doc_match_report_json,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GradeResponse) Reset() {
	*x = GradeResponse{}
	mi := &file_compute_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeResponse) ProtoMessage() {}

func (x *GradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeResponse.ProtoReflect.Descriptor instead.
func (*GradeResponse) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{7}
}

func (x *GradeResponse) GetTotalScore() float32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *GradeResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *GradeResponse) GetMergedContent() string {
	if x != nil {
		return x.MergedContent
	}
	return ""
}

func (x *GradeResponse) GetCodeDocMatchReportJson() string {
	if x != nil {
		return x.CodeDocMatchReportJson
	}
	return ""
}

// 1. 识别图片题号
type IdentifyQuestionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OcrText         string                 `protobuf:"bytes,1,opt,name=ocr_text,json=ocrText,proto3" json:"ocr_text,omitempty"`
	QuestionListStr string                 `protobuf:"bytes,2,opt,name=question_list_str,json=questionListStr,proto3" json:"question_list_str,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IdentifyQuestionRequest) Reset() {
	*x = IdentifyQuestionRequest{}
	mi := &file_compute_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyQuestionRequest) ProtoMessage() {}

func (x *IdentifyQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyQuestionRequest.ProtoReflect.Descriptor instead.
func (*IdentifyQuestionRequest) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{8}
}

func (x *IdentifyQuestionRequest) GetOcrText() string {
	if x != nil {
		return x.OcrText
	}
	return ""
}

func (x *IdentifyQuestionRequest) GetQuestionListStr() string {
	if x != nil {
		return x.QuestionListStr
	}
	return ""
}

type IdentifyQuestionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QuestionNumber int32                  `protobuf:"varint,1,opt,name=question_number,json=questionNumber,proto3" json:"question_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IdentifyQuestionResponse) Reset() {
	*x = IdentifyQuestionResponse{}
	mi := &file_compute_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyQuestionResponse) ProtoMessage() {}

func (x *IdentifyQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyQuestionResponse.ProtoReflect.Descriptor instead.
func (*IdentifyQuestionResponse) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{9}
}

func (x *IdentifyQuestionResponse) GetQuestionNumber() int32 {
	if x != nil {
		return x.QuestionNumber
	}
	return 0
}

// 2. 批改单道题目
type GradeExamQuestionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QuestionText    string                 `protobuf:"bytes,1,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	StandardAnswer  string                 `protobuf:"bytes,2,opt,name=standard_answer,json=standardAnswer,proto3" json:"standard_answer,omitempty"`
	Rubric          string                 `protobuf:"bytes,3,opt,name=rubric,proto3" json:"rubric,omitempty"`
	MaxScore        float32                `protobuf:"fixed32,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	FullStudentText string                 `protobuf:"bytes,5,opt,name=full_student_text,json=fullStudentText,proto3" json:"full_student_text,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GradeExamQuestionRequest) Reset() {
	*x = GradeExamQuestionRequest{}
	mi := &file_compute_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeExamQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeExamQuestionRequest) ProtoMessage() {}

func (x *GradeExamQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeExamQuestionRequest.ProtoReflect.Descriptor instead.
func (*GradeExamQuestionRequest) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{10}
}

func (x *GradeExamQuestionRequest) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *GradeExamQuestionRequest) GetStandardAnswer() string {
	if x != nil {
		return x.StandardAnswer
	}
	return ""
}

func (x *GradeExamQuestionRequest) GetRubric() string {
	if x != nil {
		return x.Rubric
	}
	return ""
}

func (x *GradeExamQuestionRequest) GetMaxScore() float32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *GradeExamQuestionRequest) GetFullStudentText() string {
	if x != nil {
		return x.FullStudentText
	}
	return ""
}

type GradeExamQuestionResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Score                  float32                `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	Feedback               string                 `protobuf:"bytes,2,opt,name=feedback,proto3" json:"feedback,omitempty"`
	StudentAnswerExtracted string                 `protobuf:"bytes,3,opt,name=student_answer_extracted,json=studentAnswerExtracted,proto3" json:"student_answer_extracted,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GradeExamQuestionResponse) Reset() {
	*x = GradeExamQuestionResponse{}
	mi := &file_compute_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeExamQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeExamQuestionResponse) ProtoMessage() {}

func (x *GradeExamQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeExamQuestionResponse.ProtoReflect.Descriptor instead.
func (*GradeExamQuestionResponse) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{11}
}

func (x *GradeExamQuestionResponse) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GradeExamQuestionResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *GradeExamQuestionResponse) GetStudentAnswerExtracted() string {
	if x != nil {
		return x.StudentAnswerExtracted
	}
	return ""
}

// 3. 试卷总评
type SummarizeExamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllFeedback   []string               `protobuf:"bytes,1,rep,name=all_feedback,json=allFeedback,proto3" json:"all_feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeExamRequest) Reset() {
	*x = SummarizeExamRequest{}
	mi := &file_compute_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeExamRequest) ProtoMessage() {}

func (x *SummarizeExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeExamRequest.ProtoReflect.Descriptor instead.
func (*SummarizeExamRequest) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{12}
}

func (x *SummarizeExamRequest) GetAllFeedback() []string {
	if x != nil {
		return x.AllFeedback
	}
	return nil
}

type SummarizeExamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SummaryReport string                 `protobuf:"bytes,1,opt,name=summary_report,json=summaryReport,proto3" json:"summary_report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeExamResponse) Reset() {
	*x = SummarizeExamResponse{}
	mi := &file_compute_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeExamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeExamResponse) ProtoMessage() {}

func (x *SummarizeExamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeExamResponse.ProtoReflect.Descriptor instead.
func (*SummarizeExamResponse) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{13}
}

func (x *SummarizeExamResponse) GetSummaryReport() string {
	if x != nil {
		return x.SummaryReport
	}
	return ""
}

// 4. 成绩池化
type PoolScoresRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId   string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	ScoresDataJson string                 `protobuf:"bytes,2,opt,name=scores_data_json,json=scoresDataJson,proto3" json:"scores_data_json,omitempty"` // JSON格式的批量成绩数据
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PoolScoresRequest) Reset() {
	*x = PoolScoresRequest{}
	mi := &file_compute_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolScoresRequest) ProtoMessage() {}

func (x *PoolScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolScoresRequest.ProtoReflect.Descriptor instead.
func (*PoolScoresRequest) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{14}
}

func (x *PoolScoresRequest) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *PoolScoresRequest) GetScoresDataJson() string {
	if x != nil {
		return x.ScoresDataJson
	}
	return ""
}

type PoolScoresResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PooledResultsJson string                 `protobuf:"bytes,2,opt,name=pooled_results_json,json=pooledResultsJson,proto3" json:"pooled_results_json,omitempty"` // JSON格式的池化结果
	ErrorMessage      string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PoolScoresResponse) Reset() {
	*x = PoolScoresResponse{}
	mi := &file_compute_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolScoresResponse) ProtoMessage() {}

func (x *PoolScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolScoresResponse.ProtoReflect.Descriptor instead.
func (*PoolScoresResponse) Descriptor() ([]byte, []int) {
	return file_compute_service_proto_rawDescGZIP(), []int{15}
}

func (x *PoolScoresResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PoolScoresResponse) GetPooledResultsJson() string {
	if x != nil {
		return x.PooledResultsJson
	}
	return ""
}

func (x *PoolScoresResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_compute_service_proto protoreflect.FileDescriptor

const file_compute_service_proto_rawDesc = "" +
	"\n" +
	"\x15compute_service.proto\x12\acompute\"O\n" +
	"\x0eExtractRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\ffile_content\x18\x02 \x01(\fR\vfileContent\"4\n" +
	"\x0fExtractResponse\x12!\n" +
	"\ftext_content\x18\x01 \x01(\tR\vtextContent\"\xa7\x01\n" +
	"\x11PlagiarismRequest\x12Q\n" +
	"\rstudent_texts\x18\x01 \x03(\v2,.compute.PlagiarismRequest.StudentTextsEntryR\fstudentTexts\x1a?\n" +
	"\x11StudentTextsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x12PlagiarismResponse\x126\n" +
	"\x17plagiarism_results_json\x18\x01 \x01(\tR\x15plagiarismResultsJson\"0\n" +
	"\vAIGCRequest\x12!\n" +
	"\ftext_content\x18\x01 \x01(\tR\vtextContent\"8\n" +
	"\fAIGCResponse\x12(\n" +
	"\x10aigc_report_json\x18\x01 \x01(\tR\x0eaigcReportJson\"\xef\x01\n" +
	"\fGradeRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x1f\n" +
	"\vrubric_json\x18\x03 \x01(\tR\n" +
	"rubricJson\x12!\n" +
	"\fstudent_text\x18\x04 \x01(\tR\vstudentText\x126\n" +
	"\x17plagiarism_reports_json\x18\x05 \x01(\tR\x15plagiarismReportsJson\x12(\n" +
	"\x10aigc_report_json\x18\x06 \x01(\tR\x0eaigcReportJson\"\xaf\x01\n" +
	"\rGradeResponse\x12\x1f\n" +
	"\vtotal_score\x18\x01 \x01(\x02R\n" +
	"totalScore\x12\x1a\n" +
	"\bfeedback\x18\x02 \x01(\tR\bfeedback\x12%\n" +
	"\x0emerged_content\x18\x03 \x01(\tR\rmergedContent\x12:\n" +
	"\x1acode_doc_match_report_json\x18\x04 \x01(\tR\x16codeDocMatchReportJson\"`\n" +
	"\x17IdentifyQuestionRequest\x12\x19\n" +
	"\bocr_text\x18\x01 \x01(\tR\aocrText\x12*\n" +
	"\x11question_list_str\x18\x02 \x01(\tR\x0fquestionListStr\"C\n" +
	"\x18IdentifyQuestionResponse\x12'\n" +
	"\x0fquestion_number\x18\x01 \x01(\x05R\x0equestionNumber\"\xc9\x01\n" +
	"\x18GradeExamQuestionRequest\x12#\n" +
	"\rquestion_text\x18\x01 \x01(\tR\fquestionText\x12'\n" +
	"\x0fstandard_answer\x18\x02 \x01(\tR\x0estandardAnswer\x12\x16\n" +
	"\x06rubric\x18\x03 \x01(\tR\x06rubric\x12\x1b\n" +
	"\tmax_score\x18\x04 \x01(\x02R\bmaxScore\x12*\n" +
	"\x11full_student_text\x18\x05 \x01(\tR\x0ffullStudentText\"\x87\x01\n" +
	"\x19GradeExamQuestionResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x02R\x05score\x12\x1a\n" +
	"\bfeedback\x18\x02 \x01(\tR\bfeedback\x128\n" +
	"\x18student_answer_extracted\x18\x03 \x01(\tR\x16studentAnswerExtracted\"9\n" +
	"\x14SummarizeExamRequest\x12!\n" +
	"\fall_feedback\x18\x01 \x03(\tR\vallFeedback\">\n" +
	"\x15SummarizeExamResponse\x12%\n" +
	"\x0esummary_report\x18\x01 \x01(\tR\rsummaryReport\"b\n" +
	"\x11PoolScoresRequest\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12(\n" +
	"\x10scores_data_json\x18\x02 \x01(\tR\x0escoresDataJson\"\x83\x01\n" +
	"\x12PoolScoresResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x13pooled_results_json\x18\x02 \x01(\tR\x11pooledResultsJson\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\xeb\x04\n" +
	"\x0eComputeService\x12@\n" +
	"\vExtractText\x12\x17.compute.ExtractRequest\x1a\x18.compute.ExtractResponse\x12J\n" +
	"\x0fCheckPlagiarism\x12\x1a.compute.PlagiarismRequest\x1a\x1b.compute.PlagiarismResponse\x129\n" +
	"\n" +
	"DetectAIGC\x12\x14.compute.AIGCRequest\x1a\x15.compute.AIGCResponse\x12>\n" +
	"\rGradeHomework\x12\x15.compute.GradeRequest\x1a\x16.compute.GradeResponse\x12]\n" +
	"\x16IdentifyQuestionNumber\x12 .compute.IdentifyQuestionRequest\x1a!.compute.IdentifyQuestionResponse\x12Z\n" +
	"\x11GradeExamQuestion\x12!.compute.GradeExamQuestionRequest\x1a\".compute.GradeExamQuestionResponse\x12N\n" +
	"\rSummarizeExam\x12\x1d.compute.SummarizeExamRequest\x1a\x1e.compute.SummarizeExamResponse\x12E\n" +
	"\n" +
	"PoolScores\x12\x1a.compute.PoolScoresRequest\x1a\x1b.compute.PoolScoresResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_compute_service_proto_rawDescOnce sync.Once
	file_compute_service_proto_rawDescData []byte
)

func file_compute_service_proto_rawDescGZIP() []byte {
	file_compute_service_proto_rawDescOnce.Do(func() {
		file_compute_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compute_service_proto_rawDesc), len(file_compute_service_proto_rawDesc)))
	})
	return file_compute_service_proto_rawDescData
}

var file_compute_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_compute_service_proto_goTypes = []any{
	(*ExtractRequest)(nil),            // 0: compute.ExtractRequest
	(*ExtractResponse)(nil),           // 1: compute.ExtractResponse
	(*PlagiarismRequest)(nil),         // 2: compute.PlagiarismRequest
	(*PlagiarismResponse)(nil),        // 3: compute.PlagiarismResponse
	(*AIGCRequest)(nil),               // 4: compute.AIGCRequest
	(*AIGCResponse)(nil),              // 5: compute.AIGCResponse
	(*GradeRequest)(nil),              // 6: compute.GradeRequest
	(*GradeResponse)(nil),             // 7: compute.GradeResponse
	(*IdentifyQuestionRequest)(nil),   // 8: compute.IdentifyQuestionRequest
	(*IdentifyQuestionResponse)(nil),  // 9: compute.IdentifyQuestionResponse
	(*GradeExamQuestionRequest)(nil),  // 10: compute.GradeExamQuestionRequest
	(*GradeExamQuestionResponse)(nil), // 11: compute.GradeExamQuestionResponse
	(*SummarizeExamRequest)(nil),      // 12: compute.SummarizeExamRequest
	(*SummarizeExamResponse)(nil),     // 13: compute.SummarizeExamResponse
	(*PoolScoresRequest)(nil),         // 14: compute.PoolScoresRequest
	(*PoolScoresResponse)(nil),        // 15: compute.PoolScoresResponse
	nil,                               // 16: compute.PlagiarismRequest.StudentTextsEntry
}
var file_compute_service_proto_depIdxs = []int32{
	16, // 0: compute.PlagiarismRequest.student_texts:type_name -> compute.PlagiarismRequest.StudentTextsEntry
	0,  // 1: compute.ComputeService.ExtractText:input_type -> compute.ExtractRequest
	2,  // 2: compute.ComputeService.CheckPlagiarism:input_type -> compute.PlagiarismRequest
	4,  // 3: compute.ComputeService.DetectAIGC:input_type -> compute.AIGCRequest
	6,  // 4: compute.ComputeService.GradeHomework:input_type -> compute.GradeRequest
	8,  // 5: compute.ComputeService.IdentifyQuestionNumber:input_type -> compute.IdentifyQuestionRequest
	10, // 6: compute.ComputeService.GradeExamQuestion:input_type -> compute.GradeExamQuestionRequest
	12, // 7: compute.ComputeService.SummarizeExam:input_type -> compute.SummarizeExamRequest
	14, // 8: compute.ComputeService.PoolScores:input_type -> compute.PoolScoresRequest
	1,  // 9: compute.ComputeService.ExtractText:output_type -> compute.ExtractResponse
	3,  // 10: compute.ComputeService.CheckPlagiarism:output_type -> compute.PlagiarismResponse
	5,  // 11: compute.ComputeService.DetectAIGC:output_type -> compute.AIGCResponse
	7,  // 12: compute.ComputeService.GradeHomework:output_type -> compute.GradeResponse
	9,  // 13: compute.ComputeService.IdentifyQuestionNumber:output_type -> compute.IdentifyQuestionResponse
	11, // 14: compute.ComputeService.GradeExamQuestion:output_type -> compute.GradeExamQuestionResponse
	13, // 15: compute.ComputeService.SummarizeExam:output_type -> compute.SummarizeExamResponse
	15, // 16: compute.ComputeService.PoolScores:output_type -> compute.PoolScoresResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_compute_service_proto_init() }
func file_compute_service_proto_init() {
	if File_compute_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compute_service_proto_rawDesc), len(file_compute_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compute_service_proto_goTypes,
		DependencyIndexes: file_compute_service_proto_depIdxs,
		MessageInfos:      file_compute_service_proto_msgTypes,
	}.Build()
	File_compute_service_proto = out.File
	file_compute_service_proto_goTypes = nil
	file_compute_service_proto_depIdxs = nil
}
