// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: compute_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComputeService_ExtractText_FullMethodName            = "/compute.ComputeService/ExtractText"
	ComputeService_CheckPlagiarism_FullMethodName        = "/compute.ComputeService/CheckPlagiarism"
	ComputeService_DetectAIGC_FullMethodName             = "/compute.ComputeService/DetectAIGC"
	ComputeService_GradeHomework_FullMethodName          = "/compute.ComputeService/GradeHomework"
	ComputeService_IdentifyQuestionNumber_FullMethodName = "/compute.ComputeService/IdentifyQuestionNumber"
	ComputeService_GradeExamQuestion_FullMethodName      = "/compute.ComputeService/GradeExamQuestion"
	ComputeService_SummarizeExam_FullMethodName          = "/compute.ComputeService/SummarizeExam"
)

// ComputeServiceClient is the client API for ComputeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComputeServiceClient interface {
	// 1. 提取文本
	ExtractText(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
	// 2. 全局作业查重
	CheckPlagiarism(ctx context.Context, in *PlagiarismRequest, opts ...grpc.CallOption) (*PlagiarismResponse, error)
	// 3. AIGC 检测
	DetectAIGC(ctx context.Context, in *AIGCRequest, opts ...grpc.CallOption) (*AIGCResponse, error)
	// 4. LLM 智能评分 (内含代码文档匹配度分析)
	GradeHomework(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradeResponse, error)
	// 试卷批改服务
	IdentifyQuestionNumber(ctx context.Context, in *IdentifyQuestionRequest, opts ...grpc.CallOption) (*IdentifyQuestionResponse, error)
	GradeExamQuestion(ctx context.Context, in *GradeExamQuestionRequest, opts ...grpc.CallOption) (*GradeExamQuestionResponse, error)
	SummarizeExam(ctx context.Context, in *SummarizeExamRequest, opts ...grpc.CallOption) (*SummarizeExamResponse, error)
}

type computeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComputeServiceClient(cc grpc.ClientConnInterface) ComputeServiceClient {
	return &computeServiceClient{cc}
}

func (c *computeServiceClient) ExtractText(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, ComputeService_ExtractText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) CheckPlagiarism(ctx context.Context, in *PlagiarismRequest, opts ...grpc.CallOption) (*PlagiarismResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlagiarismResponse)
	err := c.cc.Invoke(ctx, ComputeService_CheckPlagiarism_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) DetectAIGC(ctx context.Context, in *AIGCRequest, opts ...grpc.CallOption) (*AIGCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIGCResponse)
	err := c.cc.Invoke(ctx, ComputeService_DetectAIGC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) GradeHomework(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeResponse)
	err := c.cc.Invoke(ctx, ComputeService_GradeHomework_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) IdentifyQuestionNumber(ctx context.Context, in *IdentifyQuestionRequest, opts ...grpc.CallOption) (*IdentifyQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentifyQuestionResponse)
	err := c.cc.Invoke(ctx, ComputeService_IdentifyQuestionNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) GradeExamQuestion(ctx context.Context, in *GradeExamQuestionRequest, opts ...grpc.CallOption) (*GradeExamQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeExamQuestionResponse)
	err := c.cc.Invoke(ctx, ComputeService_GradeExamQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) SummarizeExam(ctx context.Context, in *SummarizeExamRequest, opts ...grpc.CallOption) (*SummarizeExamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummarizeExamResponse)
	err := c.cc.Invoke(ctx, ComputeService_SummarizeExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComputeServiceServer is the server API for ComputeService service.
// All implementations must embed UnimplementedComputeServiceServer
// for forward compatibility.
type ComputeServiceServer interface {
	// 1. 提取文本
	ExtractText(context.Context, *ExtractRequest) (*ExtractResponse, error)
	// 2. 全局作业查重
	CheckPlagiarism(context.Context, *PlagiarismRequest) (*PlagiarismResponse, error)
	// 3. AIGC 检测
	DetectAIGC(context.Context, *AIGCRequest) (*AIGCResponse, error)
	// 4. LLM 智能评分 (内含代码文档匹配度分析)
	GradeHomework(context.Context, *GradeRequest) (*GradeResponse, error)
	// 试卷批改服务
	IdentifyQuestionNumber(context.Context, *IdentifyQuestionRequest) (*IdentifyQuestionResponse, error)
	GradeExamQuestion(context.Context, *GradeExamQuestionRequest) (*GradeExamQuestionResponse, error)
	SummarizeExam(context.Context, *SummarizeExamRequest) (*SummarizeExamResponse, error)
	mustEmbedUnimplementedComputeServiceServer()
}

// UnimplementedComputeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComputeServiceServer struct{}

func (UnimplementedComputeServiceServer) ExtractText(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractText not implemented")
}
func (UnimplementedComputeServiceServer) CheckPlagiarism(context.Context, *PlagiarismRequest) (*PlagiarismResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPlagiarism not implemented")
}
func (UnimplementedComputeServiceServer) DetectAIGC(context.Context, *AIGCRequest) (*AIGCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectAIGC not implemented")
}
func (UnimplementedComputeServiceServer) GradeHomework(context.Context, *GradeRequest) (*GradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GradeHomework not implemented")
}
func (UnimplementedComputeServiceServer) IdentifyQuestionNumber(context.Context, *IdentifyQuestionRequest) (*IdentifyQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IdentifyQuestionNumber not implemented")
}
func (UnimplementedComputeServiceServer) GradeExamQuestion(context.Context, *GradeExamQuestionRequest) (*GradeExamQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GradeExamQuestion not implemented")
}
func (UnimplementedComputeServiceServer) SummarizeExam(context.Context, *SummarizeExamRequest) (*SummarizeExamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SummarizeExam not implemented")
}
func (UnimplementedComputeServiceServer) mustEmbedUnimplementedComputeServiceServer() {}
func (UnimplementedComputeServiceServer) testEmbeddedByValue()                        {}

// UnsafeComputeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputeServiceServer will
// result in compilation errors.
type UnsafeComputeServiceServer interface {
	mustEmbedUnimplementedComputeServiceServer()
}

func RegisterComputeServiceServer(s grpc.ServiceRegistrar, srv ComputeServiceServer) {
	// If the following call panics, it indicates UnimplementedComputeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComputeService_ServiceDesc, srv)
}

func _ComputeService_ExtractText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).ExtractText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_ExtractText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).ExtractText(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_CheckPlagiarism_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlagiarismRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).CheckPlagiarism(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_CheckPlagiarism_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).CheckPlagiarism(ctx, req.(*PlagiarismRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_DetectAIGC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIGCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).DetectAIGC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_DetectAIGC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).DetectAIGC(ctx, req.(*AIGCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_GradeHomework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).GradeHomework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_GradeHomework_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).GradeHomework(ctx, req.(*GradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_IdentifyQuestionNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentifyQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).IdentifyQuestionNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_IdentifyQuestionNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).IdentifyQuestionNumber(ctx, req.(*IdentifyQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_GradeExamQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeExamQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).GradeExamQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_GradeExamQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).GradeExamQuestion(ctx, req.(*GradeExamQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_SummarizeExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).SummarizeExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_SummarizeExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).SummarizeExam(ctx, req.(*SummarizeExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComputeService_ServiceDesc is the grpc.ServiceDesc for ComputeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComputeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compute.ComputeService",
	HandlerType: (*ComputeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractText",
			Handler:    _ComputeService_ExtractText_Handler,
		},
		{
			MethodName: "CheckPlagiarism",
			Handler:    _ComputeService_CheckPlagiarism_Handler,
		},
		{
			MethodName: "DetectAIGC",
			Handler:    _ComputeService_DetectAIGC_Handler,
		},
		{
			MethodName: "GradeHomework",
			Handler:    _ComputeService_GradeHomework_Handler,
		},
		{
			MethodName: "IdentifyQuestionNumber",
			Handler:    _ComputeService_IdentifyQuestionNumber_Handler,
		},
		{
			MethodName: "GradeExamQuestion",
			Handler:    _ComputeService_GradeExamQuestion_Handler,
		},
		{
			MethodName: "SummarizeExam",
			Handler:    _ComputeService_SummarizeExam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compute_service.proto",
}
