# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import compute_service_pb2 as compute__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in compute_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComputeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractText = channel.unary_unary(
                '/compute.ComputeService/ExtractText',
                request_serializer=compute__service__pb2.ExtractRequest.SerializeToString,
                response_deserializer=compute__service__pb2.ExtractResponse.FromString,
                _registered_method=True)
        self.CheckPlagiarism = channel.unary_unary(
                '/compute.ComputeService/CheckPlagiarism',
                request_serializer=compute__service__pb2.PlagiarismRequest.SerializeToString,
                response_deserializer=compute__service__pb2.PlagiarismResponse.FromString,
                _registered_method=True)
        self.DetectAIGC = channel.unary_unary(
                '/compute.ComputeService/DetectAIGC',
                request_serializer=compute__service__pb2.AIGCRequest.SerializeToString,
                response_deserializer=compute__service__pb2.AIGCResponse.FromString,
                _registered_method=True)
        self.GradeHomework = channel.unary_unary(
                '/compute.ComputeService/GradeHomework',
                request_serializer=compute__service__pb2.GradeRequest.SerializeToString,
                response_deserializer=compute__service__pb2.GradeResponse.FromString,
                _registered_method=True)
        self.IdentifyQuestionNumber = channel.unary_unary(
                '/compute.ComputeService/IdentifyQuestionNumber',
                request_serializer=compute__service__pb2.IdentifyQuestionRequest.SerializeToString,
                response_deserializer=compute__service__pb2.IdentifyQuestionResponse.FromString,
                _registered_method=True)
        self.GradeExamQuestion = channel.unary_unary(
                '/compute.ComputeService/GradeExamQuestion',
                request_serializer=compute__service__pb2.GradeExamQuestionRequest.SerializeToString,
                response_deserializer=compute__service__pb2.GradeExamQuestionResponse.FromString,
                _registered_method=True)
        self.SummarizeExam = channel.unary_unary(
                '/compute.ComputeService/SummarizeExam',
                request_serializer=compute__service__pb2.SummarizeExamRequest.SerializeToString,
                response_deserializer=compute__service__pb2.SummarizeExamResponse.FromString,
                _registered_method=True)
        self.PoolScores = channel.unary_unary(
                '/compute.ComputeService/PoolScores',
                request_serializer=compute__service__pb2.PoolScoresRequest.SerializeToString,
                response_deserializer=compute__service__pb2.PoolScoresResponse.FromString,
                _registered_method=True)
        self.FetchPortalHomework = channel.unary_unary(
                '/compute.ComputeService/FetchPortalHomework',
                request_serializer=compute__service__pb2.FetchRequest.SerializeToString,
                response_deserializer=compute__service__pb2.FetchResponse.FromString,
                _registered_method=True)


class ComputeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractText(self, request, context):
        """1. 提取文本
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPlagiarism(self, request, context):
        """2. 全局作业查重
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectAIGC(self, request, context):
        """3. AIGC 检测
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GradeHomework(self, request, context):
        """4. LLM 智能评分 (内含代码文档匹配度分析)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IdentifyQuestionNumber(self, request, context):
        """试卷批改服务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GradeExamQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeExam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PoolScores(self, request, context):
        """成绩池化服务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchPortalHomework(self, request, context):
        """教务系统作业抓取服务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractText': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractText,
                    request_deserializer=compute__service__pb2.ExtractRequest.FromString,
                    response_serializer=compute__service__pb2.ExtractResponse.SerializeToString,
            ),
            'CheckPlagiarism': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPlagiarism,
                    request_deserializer=compute__service__pb2.PlagiarismRequest.FromString,
                    response_serializer=compute__service__pb2.PlagiarismResponse.SerializeToString,
            ),
            'DetectAIGC': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectAIGC,
                    request_deserializer=compute__service__pb2.AIGCRequest.FromString,
                    response_serializer=compute__service__pb2.AIGCResponse.SerializeToString,
            ),
            'GradeHomework': grpc.unary_unary_rpc_method_handler(
                    servicer.GradeHomework,
                    request_deserializer=compute__service__pb2.GradeRequest.FromString,
                    response_serializer=compute__service__pb2.GradeResponse.SerializeToString,
            ),
            'IdentifyQuestionNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.IdentifyQuestionNumber,
                    request_deserializer=compute__service__pb2.IdentifyQuestionRequest.FromString,
                    response_serializer=compute__service__pb2.IdentifyQuestionResponse.SerializeToString,
            ),
            'GradeExamQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GradeExamQuestion,
                    request_deserializer=compute__service__pb2.GradeExamQuestionRequest.FromString,
                    response_serializer=compute__service__pb2.GradeExamQuestionResponse.SerializeToString,
            ),
            'SummarizeExam': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeExam,
                    request_deserializer=compute__service__pb2.SummarizeExamRequest.FromString,
                    response_serializer=compute__service__pb2.SummarizeExamResponse.SerializeToString,
            ),
            'PoolScores': grpc.unary_unary_rpc_method_handler(
                    servicer.PoolScores,
                    request_deserializer=compute__service__pb2.PoolScoresRequest.FromString,
                    response_serializer=compute__service__pb2.PoolScoresResponse.SerializeToString,
            ),
            'FetchPortalHomework': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchPortalHomework,
                    request_deserializer=compute__service__pb2.FetchRequest.FromString,
                    response_serializer=compute__service__pb2.FetchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'compute.ComputeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('compute.ComputeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComputeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compute.ComputeService/ExtractText',
            compute__service__pb2.ExtractRequest.SerializeToString,
            compute__service__pb2.ExtractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPlagiarism(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compute.ComputeService/CheckPlagiarism',
            compute__service__pb2.PlagiarismRequest.SerializeToString,
            compute__service__pb2.PlagiarismResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectAIGC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compute.ComputeService/DetectAIGC',
            compute__service__pb2.AIGCRequest.SerializeToString,
            compute__service__pb2.AIGCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GradeHomework(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compute.ComputeService/GradeHomework',
            compute__service__pb2.GradeRequest.SerializeToString,
            compute__service__pb2.GradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IdentifyQuestionNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compute.ComputeService/IdentifyQuestionNumber',
            compute__service__pb2.IdentifyQuestionRequest.SerializeToString,
            compute__service__pb2.IdentifyQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GradeExamQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compute.ComputeService/GradeExamQuestion',
            compute__service__pb2.GradeExamQuestionRequest.SerializeToString,
            compute__service__pb2.GradeExamQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeExam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compute.ComputeService/SummarizeExam',
            compute__service__pb2.SummarizeExamRequest.SerializeToString,
            compute__service__pb2.SummarizeExamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PoolScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compute.ComputeService/PoolScores',
            compute__service__pb2.PoolScoresRequest.SerializeToString,
            compute__service__pb2.PoolScoresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchPortalHomework(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compute.ComputeService/FetchPortalHomework',
            compute__service__pb2.FetchRequest.SerializeToString,
            compute__service__pb2.FetchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
